# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGE', '0003_absence_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='start_date',
        ),
        migrations.AddField(
            model_name='absence',
            name='absence_type',
            field=models.CharField(choices=[('WFH', 'Work from home'), ('LV', 'Take a leave')], default='LV', max_length=3),
        ),
        migrations.AddField(
            model_name='absence',
            name='end_date_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='absence',
            name='start_date_time',
            field=models.DateTimeField(default=None),
        ),
    ]
