# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGE', '0005_auto_20170716_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_date_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
