# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGE', '0006_auto_20170716_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
