# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 11:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGE', '0010_auto_20170717_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date(2017, 7, 19)),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 19, 16, 59, 24, 643439)),
        ),
        migrations.AlterField(
            model_name='task',
            name='employees',
            field=models.ManyToManyField(to='PGE.Employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.date(2017, 7, 19)),
        ),
    ]
