# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PGE', '0011_auto_20170719_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date(2017, 7, 29)),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 29, 18, 13, 38, 784992)),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.date(2017, 7, 29)),
        ),
        migrations.AddField(
            model_name='link',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PGE.Project'),
        ),
    ]
